import os, time
print("downloading.")
time.sleep(0.9)
os.system("pip install requests")
os.system("pip install colorama")
os.system("pip install os")
os.system("pip install time")
os.system("pip install string")
os.system("pip install colored")
os.system("pip install random")
os.system("pip install instabot")
os.system("pip install sys")
os.system("pip install n")
os.system("pip install mm")
os.system("pip install webbrowser")
os.system("pip install youtube_dl")
os.system("pip install pyfiglet")
os.system("pip install pafy")
os.system("pip install tqdm")
os.system("pip install requests_toolbelt")
os.system("pip install urllib")
os.system("pip install secrets")
os.system("pip install uuid")
os.system("pip install bs4")
os.system("pip install requests")
os.system("pip install pyTelegramBotAPI")
os.system("pip install types")
os.system("pip install telebot")
os.system("pip install bs4")
time.sleep(0.9)
print('\nDone downloading☑️')


